### ISSUE TITLE
Not tagged as monospace or not truly monospace?

### ISSUE THREAD

**Issue by adam-c-anderson** [SSNikolaevich/DejaVuSansCode#12]
Forgive me if I don't use the right terms here as I am not a font developer. :) None of my tools seem to "think" that this font is a monospace font. Examples: 

* Visual Studio highlights in bold all fonts that it detects are monospace in its font dropdown.
* gVim and the Windows terminal do not even show the font as an option in the font picker because it's not detected as a monospace font.

Is this known and intentional?

**Comment by SSNikolaevich** [comment]
I'm not a font developer too. I just added a few ligatures into font I use in order to make my code more readable. :) As this ligatures has double (triple and so on) width, it is no longer a monospace font. I don't know how mark it as monospace.

**Comment by adam-c-anderson** [comment]
OK. FWIW, Fira Code is monospace with ligatures (and appears as such in the tools listed above), so perhaps you could look at how it's done there, if you have the time and interest.
