### ISSUE TITLE
Not all symbols (as shown in the README) work

### ISSUE THREAD

**Issue by adityavm** [SSNikolaevich/DejaVuSansCode#4]
<img width="343" alt="screen shot 2017-07-23 at 4 59 24 pm" src="https://user-images.githubusercontent.com/80849/28498985-700a7f94-6fc8-11e7-823a-b2a871063a6e.png">

In Atom :atom: (if that matters) the `<--`, `<-`, `->` and `=>` symbols don't get replaced by ligatures.

Am I missing a setting or a config?

**Comment by SSNikolaevich** [comment]
Checked this issue on Atom 1.18.0 (Debian 8 x64). All symbols are displayed correctly. Make sure all font variants (bold, italic etc.) are installed. Some code highlight schemes uses italic/bold glyphs for mathematic operations.
![screenshot8](https://user-images.githubusercontent.com/900852/28511315-bfd38210-705d-11e7-8683-c4d888c8e876.png)
Also '=>' ligature currently present only in master branch and not yet released.

**Comment by adityavm** [comment]
@SSNikolaevich thank you, confirmed it works in plain text . The JS syntax was causing the arrows not to be converted
