### ISSUE TITLE
Ligature for `<=>`

### ISSUE THREAD

**Issue by areyes-ut** [SSNikolaevich/DejaVuSansCode#5]
Only `<=` is converted, and `>` is left behind.  It should be one single ligature/character.

This is used in Ruby, for example, for comparison blocks/methods.  See https://ruby-doc.org/core-2.4.1/Enumerable.html#method-i-sort_by

**Comment by SSNikolaevich** [comment]
Added ligature for '<=>' (de6fef989fa2c2283232bf3a9f10dff9542c00ba). Hinting instructions will be ready in a couple of days.

**Comment by SSNikolaevich** [comment]
Fully implemented to 3b9b5458d1fc0c6be79942ab841b896bf45c8e68
